---
- name: Install Python packages.
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - boto
    state: present

- name: Clear existent Oracle Client folder
  shell: gsutil -m rm -r gs://{{ gcs_bucket }}/data/oracle_client
  ignore_errors: yes

# tasks file for ansible-oracle-client
- name: Download and extract
  ansible.builtin.unarchive:
    src: "{{ url_client_installer }}"
    dest: ./
    remote_src: yes

- name: Create lib directory
  ansible.builtin.file:
    path: ./{{ client_folder }}/lib
    state: directory
    mode: '0755'

- name: Create a symbolic link libclntsh.so
  ansible.builtin.file:
    src: ../libclntsh.so
    dest: ./{{ client_folder }}/lib/libclntsh.so
    state: link
    force: yes

- name: Create a symbolic link libnnz19.so
  ansible.builtin.file:
    src: ../libnnz19.so
    dest: ./{{ client_folder }}/lib/libnnz19.so
    state: link
    force: yes

# - name: Rename dir
#   shell: mv instantclient_21_5 oracle_client

# - name: Upload Oracle Client
#   gc_storage:
#     bucket: "{{ gcs_bucket }}"
#     object: /data/oracle_client/README
#     src: ./instantclient_21_5/network/admin/README
#     mode: put
#     gs_access_key: "{{ gs_access_key }}"
#     gs_secret_key: "{{ gs_secret_key }}"

- name: Upload Oracle Client
  shell: gsutil -m cp -r ./{{ client_folder }}/ gs://{{ gcs_bucket }}/data/oracle_client